name: Markdown

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"
